  language: python
  python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
  install:
    - pip install -r requirements-test.txt
  env:
    - PYTHONPATH=.
  script:
    - py.test -vv cowdict/tests
  